name: Node.js CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Run Tests
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm test

      - name: Run Hugo
        run: hugo -d $GITHUB_WORKSPACE/public

      - name: Test HTML
        continue-on-error: true
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yaml

      - name: Archive htmltest results
        uses: actions/upload-artifact@v4
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7 # Default 90 days
